### PR TITLE
Add custom message support

### PR DESCRIPTION
**Pull request by hazebooth**
solves #4

### CODE REVIEW

**Comment by athre0z** [comment]
Thanks for the PR! Generally speaking, I'd prefer to go with an approach that is extensible towards adding more settings later on. It might be desirable to allow users to specify custom colors at some point etc.. For that, I'd suggest adding a `Settings` struct with all-`pub` members and a `Default` implementation. Also, I'd prefer using an owned string here instead of a `&'static str` to allow users to generate dynamic messages more easily. I like that you added a second function instead of changing the simple install API, I think this is a good idea.

If you have time and motivation to implement this, please let me know. Otherwise, I'll likely do it myself in the next few days -- this has been on my TODO anyways. :)

**Comment by hazebooth** [comment]
@athre0z I can do it, but I was unsure of what setting other than message to presist through the application. For now I will leave a skeleton pertaining to message and let you extend from there on out.

**Comment by athre0z** [comment]
Excellent, sounds good to me!

**Comment by hazebooth** [comment]
@athre0z is this alright? I was having trouble getting the `settings` into the actual closure (I also looked at FnBox but want to avoid nightly items) so I just clone everything, even though I know clones are the crux of some programs I couldn't find a way to pass it through. If you think of a better solution feel free to suggest it

**Comment by athre0z** [comment]
Thanks!

Builder pattern is fine with me, but I switched it to a consuming one. Because we need to turn it into an owned object, we previously had to clone the non-consuming builder anyways, pretty much killing the main selling point of the non-consuming one. I also removed the `Option<T>` from the `String` to get rid of the need for getters. I like things to be simple and for frequently accessed settings (like colors will be in the future), if gets rid of a lot of branches in the resulting code.

Regarding the clone in the closure, I changed the `PanicHandler` struct to be a reference -- the `Settings` object lives is moved into the closure, so this works out fine.

Since what appears to be the great majority of people really didn't like the current default panic message, I also changed it to to something more boring while at it.

Finally, I ran everything through rustfmt.

Please let me know if you're OK with these changes! :)

**Comment by hazebooth** [comment]
Yep, looks good

**Pull request merged**
